---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppetboard.fullname" . }}
  labels:
{{ include "puppetboard.labels" . | indent 4 }}
stringData:
  autosign_psk: {{ .Values.autosign.psk | quote }}
